PARTNER = "Intellecap"  #AFEC , Intellecap
COUNTRY = "India"
CROP = "Coffee"
YEAR = "2025"
EXCELVERSION = "SurveyCTO_GroundTruthCollectionv3"
COUNTRY_ISO3 = "IND"

MIN_SUBPLOT_AREA_SIZE =  450
MAX_SUBPLOT_AREA_SIZE =  750
MIN_GT_PLOT_AREA_SIZE = 2000
MAX_GT_PLOT_AREA_SIZE = 20000
MAX_VERTICES = 4

